// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: gsm/gsm.proto

package gsmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSmsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Phone  string `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
}

func (x *GetSmsRequest) Reset() {
	*x = GetSmsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gsm_gsm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSmsRequest) ProtoMessage() {}

func (x *GetSmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gsm_gsm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSmsRequest.ProtoReflect.Descriptor instead.
func (*GetSmsRequest) Descriptor() ([]byte, []int) {
	return file_gsm_gsm_proto_rawDescGZIP(), []int{0}
}

func (x *GetSmsRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetSmsRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type GetSmsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sms string `protobuf:"bytes,1,opt,name=sms,proto3" json:"sms,omitempty"`
}

func (x *GetSmsResponse) Reset() {
	*x = GetSmsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gsm_gsm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSmsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSmsResponse) ProtoMessage() {}

func (x *GetSmsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gsm_gsm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSmsResponse.ProtoReflect.Descriptor instead.
func (*GetSmsResponse) Descriptor() ([]byte, []int) {
	return file_gsm_gsm_proto_rawDescGZIP(), []int{1}
}

func (x *GetSmsResponse) GetSms() string {
	if x != nil {
		return x.Sms
	}
	return ""
}

type GetFlashCallRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phone string `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
}

func (x *GetFlashCallRequest) Reset() {
	*x = GetFlashCallRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gsm_gsm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFlashCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlashCallRequest) ProtoMessage() {}

func (x *GetFlashCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gsm_gsm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlashCallRequest.ProtoReflect.Descriptor instead.
func (*GetFlashCallRequest) Descriptor() ([]byte, []int) {
	return file_gsm_gsm_proto_rawDescGZIP(), []int{2}
}

func (x *GetFlashCallRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type GetFlashCallResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *GetFlashCallResponse) Reset() {
	*x = GetFlashCallResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gsm_gsm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFlashCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlashCallResponse) ProtoMessage() {}

func (x *GetFlashCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gsm_gsm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlashCallResponse.ProtoReflect.Descriptor instead.
func (*GetFlashCallResponse) Descriptor() ([]byte, []int) {
	return file_gsm_gsm_proto_rawDescGZIP(), []int{3}
}

func (x *GetFlashCallResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_gsm_gsm_proto protoreflect.FileDescriptor

var file_gsm_gsm_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x67, 0x73, 0x6d, 0x2f, 0x67, 0x73, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x67, 0x73, 0x6d, 0x22, 0x3d, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x6d, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68,
	0x6f, 0x6e, 0x65, 0x22, 0x22, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x6d, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x73, 0x6d, 0x73, 0x22, 0x2b, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x46, 0x6c,
	0x61, 0x73, 0x68, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x22, 0x2e, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x61, 0x73, 0x68,
	0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x32, 0x7d, 0x0a, 0x03, 0x47, 0x73, 0x6d, 0x12, 0x31, 0x0a, 0x06, 0x47,
	0x65, 0x74, 0x53, 0x6d, 0x73, 0x12, 0x12, 0x2e, 0x67, 0x73, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x53,
	0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x67, 0x73, 0x6d, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43,
	0x0a, 0x0c, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x18,
	0x2e, 0x67, 0x73, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x43, 0x61, 0x6c,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x67, 0x73, 0x6d, 0x2e, 0x47,
	0x65, 0x74, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x10, 0x5a, 0x0e, 0x73, 0x6e, 0x69, 0x70, 0x2e, 0x67, 0x73, 0x6d, 0x3b,
	0x67, 0x73, 0x6d, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gsm_gsm_proto_rawDescOnce sync.Once
	file_gsm_gsm_proto_rawDescData = file_gsm_gsm_proto_rawDesc
)

func file_gsm_gsm_proto_rawDescGZIP() []byte {
	file_gsm_gsm_proto_rawDescOnce.Do(func() {
		file_gsm_gsm_proto_rawDescData = protoimpl.X.CompressGZIP(file_gsm_gsm_proto_rawDescData)
	})
	return file_gsm_gsm_proto_rawDescData
}

var file_gsm_gsm_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gsm_gsm_proto_goTypes = []any{
	(*GetSmsRequest)(nil),        // 0: gsm.GetSmsRequest
	(*GetSmsResponse)(nil),       // 1: gsm.GetSmsResponse
	(*GetFlashCallRequest)(nil),  // 2: gsm.GetFlashCallRequest
	(*GetFlashCallResponse)(nil), // 3: gsm.GetFlashCallResponse
}
var file_gsm_gsm_proto_depIdxs = []int32{
	0, // 0: gsm.Gsm.GetSms:input_type -> gsm.GetSmsRequest
	2, // 1: gsm.Gsm.GetFlashCall:input_type -> gsm.GetFlashCallRequest
	1, // 2: gsm.Gsm.GetSms:output_type -> gsm.GetSmsResponse
	3, // 3: gsm.Gsm.GetFlashCall:output_type -> gsm.GetFlashCallResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gsm_gsm_proto_init() }
func file_gsm_gsm_proto_init() {
	if File_gsm_gsm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gsm_gsm_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetSmsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gsm_gsm_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetSmsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gsm_gsm_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetFlashCallRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gsm_gsm_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetFlashCallResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gsm_gsm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gsm_gsm_proto_goTypes,
		DependencyIndexes: file_gsm_gsm_proto_depIdxs,
		MessageInfos:      file_gsm_gsm_proto_msgTypes,
	}.Build()
	File_gsm_gsm_proto = out.File
	file_gsm_gsm_proto_rawDesc = nil
	file_gsm_gsm_proto_goTypes = nil
	file_gsm_gsm_proto_depIdxs = nil
}
