// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: gsm/gsm.proto

package gsmv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Gsm_SendSms_FullMethodName   = "/gsm.Gsm/SendSms"
	Gsm_FlashCall_FullMethodName = "/gsm.Gsm/FlashCall"
)

// GsmClient is the client API for Gsm service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GsmClient interface {
	SendSms(ctx context.Context, in *SendSmsRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	FlashCall(ctx context.Context, in *FlashCallRequest, opts ...grpc.CallOption) (*CommonResponse, error)
}

type gsmClient struct {
	cc grpc.ClientConnInterface
}

func NewGsmClient(cc grpc.ClientConnInterface) GsmClient {
	return &gsmClient{cc}
}

func (c *gsmClient) SendSms(ctx context.Context, in *SendSmsRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, Gsm_SendSms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gsmClient) FlashCall(ctx context.Context, in *FlashCallRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, Gsm_FlashCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GsmServer is the server API for Gsm service.
// All implementations must embed UnimplementedGsmServer
// for forward compatibility.
type GsmServer interface {
	SendSms(context.Context, *SendSmsRequest) (*CommonResponse, error)
	FlashCall(context.Context, *FlashCallRequest) (*CommonResponse, error)
	mustEmbedUnimplementedGsmServer()
}

// UnimplementedGsmServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGsmServer struct{}

func (UnimplementedGsmServer) SendSms(context.Context, *SendSmsRequest) (*CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendSms not implemented")
}
func (UnimplementedGsmServer) FlashCall(context.Context, *FlashCallRequest) (*CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FlashCall not implemented")
}
func (UnimplementedGsmServer) mustEmbedUnimplementedGsmServer() {}
func (UnimplementedGsmServer) testEmbeddedByValue()             {}

// UnsafeGsmServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GsmServer will
// result in compilation errors.
type UnsafeGsmServer interface {
	mustEmbedUnimplementedGsmServer()
}

func RegisterGsmServer(s grpc.ServiceRegistrar, srv GsmServer) {
	// If the following call pancis, it indicates UnimplementedGsmServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Gsm_ServiceDesc, srv)
}

func _Gsm_SendSms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendSmsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GsmServer).SendSms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gsm_SendSms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GsmServer).SendSms(ctx, req.(*SendSmsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gsm_FlashCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlashCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GsmServer).FlashCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gsm_FlashCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GsmServer).FlashCall(ctx, req.(*FlashCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Gsm_ServiceDesc is the grpc.ServiceDesc for Gsm service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gsm_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gsm.Gsm",
	HandlerType: (*GsmServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendSms",
			Handler:    _Gsm_SendSms_Handler,
		},
		{
			MethodName: "FlashCall",
			Handler:    _Gsm_FlashCall_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gsm/gsm.proto",
}
